# Generated by Django 5.0.6 on 2024-06-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_semester_created_at_semester_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.IntegerField(),
        ),
    ]
