# Generated by Django 5.0.6 on 2024-06-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_semester_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='name',
            new_name='sem',
        ),
    ]
