# Generated by Django 5.0.6 on 2024-06-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_name_semester_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='updated_at',
        ),
    ]
