# Generated by Django 5.0.6 on 2024-07-02 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_semester_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
