# Generated by Django 5.0.6 on 2024-07-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_semester_created_at_semester_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='sem',
        ),
        migrations.AddField(
            model_name='semester',
            name='name',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=1),
        ),
    ]
