# Generated by Django 5.0.6 on 2024-07-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_semester_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='id',
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
