# Generated by Django 5.0.6 on 2024-07-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_semester_id_alter_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
