# Generated by Django 5.0.6 on 2024-07-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_usertype_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='course_id',
        ),
    ]
