# Generated by Django 5.0.6 on 2024-07-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_course_student_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobileNumber',
            new_name='mobile_no',
        ),
    ]
